// <auto-generated />
namespace CurryMVCv3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IsTheeAGod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsTheeAGod));
        
        string IMigrationMetadata.Id
        {
            get { return "201912122238488_IsTheeA God"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
